export const EXAMPLE_ADD = 'EXAMPLE_ADD'
export const EXAMPLE_EDIT = 'EXAMPLE_EDIT'
export const EXAMPLE_DELETE = 'EXAMPLE_DELETE'

export const EXAMPLE = 'EXAMPLE'
export const EXAMPLE_PENDING = 'EXAMPLE_PENDING'
export const EXAMPLE_REJECTED = 'EXAMPLE_REJECTED'
export const EXAMPLE_FULFILLED = 'EXAMPLE_FULFILLED'